SELECT SEQ, ID, TITLE, CONTENT, REFER, STEP, "DEPTH", DELFLAG, REGDATE
	FROM ANSWERBOARD;

INSERT INTO ANSWERBOARD
	(SEQ, ID, TITLE, CONTENT, REFER, STEP, "DEPTH", DELFLAG, REGDATE)
	VALUES(100, 'USER01', '제목1', '작성된 글이 없음', 0, 0, 0, 'N', SYSDATE);

UPDATE ANSWERBOARD
	SET TITLE='업데이트 테스트', CONTENT='작성된 글이 없음'
	WHERE SEQ=12;

UPDATE ANSWERBOARD
	SET DELFLAG='Y'
	WHERE SEQ=100;