--게시판의 ROOT작성
INSERT INTO ANSWERBOARD (SEQ, ID, TITLE, 
      CONTENT, REFER, STEP, 
      "DEPTH", DELFLAG, REGDATE)
      VALUES(ANSWERBOARD_SEQ.NEXTVAL, 'USER26', '시험테스트',
             '시험테스트 확인' , (SELECT NVL(MAX(SEQ),0)+1 FROM ANSWERBOARD a),0,
             0, 'N', SYSDATE);
--게시판의 글 수정
UPDATE ANSWERBOARD SET CONTENT  = '수정된 내용 테스트'
	WHERE SEQ = '41';
--게시판의 글 삭제(UPDATE)
UPDATE ANSWERBOARD SET DELFLAG ='Y'
	WHERE SEQ ='41';
--게시판의 글 삭제(DELETE)
DELETE FROM ANSWERBOARD a 
	WHERE SEQ = '1';
--게시판의 글 상세조회
SELECT SEQ, ID, LPAD(' ', "DEPTH"*10) || TITLE, 
	CONTENT, REFER, STEP, 
	"DEPTH", DELFLAG, REGDATE
	FROM ANSWERBOARD a
	WHERE SEQ = 41;
--게시판의 글 전체 조회
SELECT SEQ, ID, LPAD(' ', "DEPTH"*10) || TITLE, 
	CONTENT, REFER, STEP, 
	"DEPTH", DELFLAG, REGDATE
	FROM ANSWERBOARD a
	ORDER BY REFER DESC , STEP ;
--답글 작성(UPDATE)
UPDATE ANSWERBOARD SET STEP =  STEP + 1 
	WHERE STEP > (SELECT STEP FROM ANSWERBOARD a WHERE SEQ='41');
--답글 작성(INSERT)
INSERT INTO ANSWERBOARD (SEQ, ID, TITLE, 
      CONTENT, REFER, STEP, 
      "DEPTH", DELFLAG, REGDATE)
      VALUES(ANSWERBOARD_SEQ.NEXTVAL, 'USER27', '답글테스트2',
      '답글테스트확인2', (SELECT REFER FROM ANSWERBOARD a WHERE SEQ='41'), (SELECT STEP+1 FROM ANSWERBOARD a WHERE SEQ='41'),
      (SELECT "DEPTH"+1 FROM ANSWERBOARD a WHERE SEQ='41'),'N',SYSDATE);
      