-- Join에 대해서 알아보자


SELECT *
	FROM PLAYER p, TEAM t;
	
SELECT *
	FROM PLAYER p CROSS JOIN TEAM t;
	
SELECT *
	FROM PLAYER p JOIN TEAM t 
	ON p.TEAM_ID * t.TEAM_ID;
	
SELECT *
	FROM PLAYER p JOIN TEAM t 
	USING(TEAM_ID);
	

SELECT COUNT(*)
	FROM PLAYER p;
SELECT COUNT(*)
	FROM TEAM t;
	
SELECT *
	FROM PLAYER p LEFT OUTER JOIN TEAM t 
	ON P.TEAM_ID = T.TEAM_ID;

SELECT *
	FROM PLAYER p, TEAM t 
	ON P.TEAM_ID = T.TEAM_ID(+);


SELECT *
	FROM PLAYER p RIGHT OUTER JOIN TEAM t 
	ON P.TEAM_ID = T.TEAM_ID;

SELECT *
	FROM PLAYER p, TEAM t 
	ON P.TEAM_ID(+) = T.TEAM_ID;

----------------------------------------------------------------------------
SELECT *
	FROM PLAYER p JOIN TEAM t 
	ON p.TEAM_ID * t.TEAM_ID;

SELECT p.PLAYER_NAME, t.TEAM_NAME, p.BACK_NO, p."POSITION",
		t.REGION_NAME, t.ADDRESS, t.HOMEPAGE
	FROM PLAYER p JOIN TEAM t 
	ON p.TEAM_ID = t.TEAM_ID;

SELECT "POSITION", BACK_NO, TEAM_ID
	FROM PLAYER p JOIN TEAM t 
	WHERE PLAYER_NAME = '곽기훈';
	
