CREATE TABLE ANSWERBOARD(
	SEQ NUMBER,
	ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	REFER NUMBER NOT NULL,
	STEP NUMBER NOT NULL,
	"DEPTH" NUMBER NOT NULL,
	DELFLAG CHAR(1) NOT NULL,
	REGDATE DATE
);
DROP SEQUENCE ANSWERBOARD_SEQ;
CREATE SEQUENCE ANSWERBOARD_SEQ START WITH 1 INCREMENT BY 1;

ALTER TABLE ANSWERBOARD ADD CONSTRAINT ANSWERBOARD_PK PRIMARY KEY (SEQ);
DELETE FROM ANSWERBOARD;
SELECT * FROM ANSWERBOARD;
-- ROOT 입력
INSERT INTO ANSWERBOARD (SEQ, ID, TITLE, 
						CONTENT, REFER, STEP, 
						"DEPTH", DELFLAG, REGDATE) 
			VALUES (ANSWERBOARD_SEQ.NEXTVAL, '사용자1', '사용자1제목1', 
					'내용1', (SELECT NVL(MAX(SEQ),0)+1 FROM ANSWERBOARD a), 0, 
					0, 'N', SYSDATE);
INSERT INTO ANSWERBOARD (SEQ, ID, TITLE, 
						CONTENT, REFER, STEP, 
						"DEPTH", DELFLAG, REGDATE) 
			VALUES (ANSWERBOARD_SEQ.NEXTVAL, '사용자2', '날씨가추워', 
					'비와서 추워', (SELECT NVL(MAX(SEQ),0)+1 FROM ANSWERBOARD a), 0, 
					0, 'N', SYSDATE);
INSERT INTO ANSWERBOARD (SEQ, ID, TITLE, 
						CONTENT, REFER, STEP, 
						"DEPTH", DELFLAG, REGDATE) 
			VALUES (ANSWERBOARD_SEQ.NEXTVAL, '사용자3', '안녕친구야', 
					'놀이터에서 만나', (SELECT NVL(MAX(SEQ),0)+1 FROM ANSWERBOARD a), 0, 
					0, 'N', SYSDATE);
				
-- ROOT 조회
SELECT  SEQ, ID, LPAD(' ', "DEPTH"*10) || TITLE, 
		CONTENT, REFER, STEP, "DEPTH", DELFLAG, REGDATE
	FROM ANSWERBOARD a	
	ORDER BY REFER DESC, STEP ;

-- 답글 입력
INSERT INTO ANSWERBOARD (SEQ, ID, TITLE, 
						CONTENT, REFER, STEP, 
						"DEPTH", DELFLAG, REGDATE) 
			VALUES (ANSWERBOARD_SEQ.NEXTVAL, '사용자6', '답글답글2', 
					'답글답글2', (SELECT REFER FROM ANSWERBOARD a WHERE SEQ='6'), (SELECT STEP+1 FROM ANSWERBOARD a WHERE SEQ='6'), 
					(SELECT "DEPTH"+1 FROM ANSWERBOARD a WHERE SEQ='6'), 'N', SYSDATE);
					
-- 답글 입력을 위한 업데이트
UPDATE ANSWERBOARD SET STEP = STEP +1
	WHERE STEP > (SELECT STEP FROM ANSWERBOARD a WHERE SEQ='6');
	

-- ROOT 상세조회
SELECT  SEQ, ID, LPAD(' ', "DEPTH"*10) || TITLE, 
		CONTENT, REFER, STEP, "DEPTH", DELFLAG, REGDATE
	FROM ANSWERBOARD a	
	WHERE SEQ = 1;
	
-- 글(ROOT, 답글) 수정
UPDATE ANSWERBOARD SET CONTENT = '수정된 내용'
	WHERE SEQ = 1;
	
-- 글 삭제(UPDATE로 DELFLAG Y로 변경)
UPDATE ANSWERBOARD SET DELFLAG ='Y'
	WHERE SEQ='1';

-- 글 삭제(관리자 REAL 삭제)
DELETE FROM ANSWERBOARD a
	WHERE SEQ='1';
	
