CREATE TABLE TOTALMEMBER(
	ID VARCHAR2(50),
	PW VARCHAR2(200) NOT NULL,
	AUTH CHAR(1) NOT NULL,
	DELFLAG CHAR(1) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT "TOTALMEMBER_PK" PRIMARY KEY(ID) ,
	CONSTRAINT "MEMBER_CK" CHECK("AUTH" IN ('U','A'))
);

ALTER TABLE TOTALMEMBER ADD (NAME VARCHAR2(100));


CREATE TABLE TOTALBOARD(
	SEQ NUMBER,
	ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(500) NOT NULL,
	CONTENT VARCHAR2(4000),
	STEP NUMBER NOT NULL,
	DEPTH NUMBER NOT NULL,
	REFER NUMBER NOT NULL,
	READCOUNT NUMBER NOT NULL,
	DELFLAG CHAR(1) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT "TOTALBOARD_PK" PRIMARY KEY (SEQ),
	CONSTRAINT "TOTALBOARD_FK" FOREIGN KEY(ID) REFERENCES "TOTALMEMBER"("ID")
);

CREATE SEQUENCE TOTALBOARD_SEQ START WITH 1 INCREMENT BY 1;


INSERT INTO TOTALMEMBER
(ID, NAME, PW, AUTH, DELFLAG, REGDATE)
VALUES('USER01', 'USER01', '1234', 'U', 'N', SYSDATE);
INSERT INTO TOTALMEMBER
(ID, NAME, PW, AUTH, DELFLAG, REGDATE)
VALUES('USER02', 'USER02', '1234', 'U', 'Y', SYSDATE);
INSERT INTO TOTALMEMBER
(ID, NAME, PW, AUTH, DELFLAG, REGDATE)
VALUES('ADMIN01', 'ADMIN01', '1234', 'A', 'Y', SYSDATE);



INSERT INTO TOTALBOARD
(SEQ, ID, TITLE, CONTENT, 
STEP, "DEPTH", REFER, 
READCOUNT, DELFLAG, REGDATE)
VALUES(TOTALBOARD_SEQ.NEXTVAL, 'USER02', 'USER01 글작성 '||TOTALBOARD_SEQ.CURRVAL,'내용 내용 글작성중 test', 
	0, 0, (SELECT NVL(MAX(REFER),0)+1 FROM TOTALBOARD ),
    0, 'N', SYSDATE);








